import type { CapacityInputs } from '@sds/shared/src/index';
import {
  calculateCapacity,
  formatBytes,
  formatCompactNumber,
} from '../../capacity';
import { useDesignStore } from '../../store/useDesignStore';

const INPUTS: Array<{
  key: keyof CapacityInputs;
  label: string;
  description: string;
  min: number;
  max?: number;
  step?: number;
}> = [
  {
    key: 'dailyActiveUsers',
    label: 'Daily active users',
    description: 'Unique users active in one day',
    min: 0,
  },
  {
    key: 'actionsPerUserPerDay',
    label: 'Actions per user / day',
    description: 'Average requests generated by each active user',
    min: 0,
    step: 0.1,
  },
  {
    key: 'readPercentage',
    label: 'Read traffic',
    description: 'Percentage of requests that are reads',
    min: 0,
    max: 100,
  },
  {
    key: 'peakTrafficMultiplier',
    label: 'Peak multiplier',
    description: 'Peak traffic compared with daily average',
    min: 1,
    step: 0.1,
  },
  {
    key: 'requestSizeBytes',
    label: 'Average request size',
    description: 'Inbound bytes per request',
    min: 0,
  },
  {
    key: 'responseSizeBytes',
    label: 'Average response size',
    description: 'Outbound bytes per request',
    min: 0,
  },
  {
    key: 'storedRecordSizeBytes',
    label: 'Stored bytes per write',
    description: 'Persisted data created by each write',
    min: 0,
  },
  {
    key: 'retentionDays',
    label: 'Retention period',
    description: 'Number of days data remains stored',
    min: 0,
  },
  {
    key: 'replicationFactor',
    label: 'Replication factor',
    description: 'Number of stored copies',
    min: 1,
  },
];

export function CapacityWorkspace() {
  const { capacity, setCapacity, components, notes, setNotes } = useDesignStore();
  const estimate = calculateCapacity(capacity);
  const readCapacity = components.reduce(
    (total, component) =>
      total + component.config.readThroughput * Math.max(1, component.config.replicas),
    0
  );
  const writeCapacity = components.reduce(
    (total, component) =>
      total + component.config.writeThroughput * Math.max(1, component.config.replicas),
    0
  );

  const applyToNfrs = () => {
    setNotes({
      ...notes,
      nonFunctionalRequirements: {
        ...notes.nonFunctionalRequirements,
        scale:
          `${formatCompactNumber(capacity.dailyActiveUsers)} DAU, ` +
          `${formatCompactNumber(estimate.peakQps)} peak QPS ` +
          `(${formatCompactNumber(estimate.peakReadQps)} reads / ` +
          `${formatCompactNumber(estimate.peakWriteQps)} writes), ` +
          `${formatBytes(estimate.retainedStorageBytes)} retained storage`,
      },
    });
  };

  return (
    <div style={workspaceStyle}>
      <div style={headingStyle}>
        <div>
          <div style={{ fontSize: 20, fontWeight: 800 }}>Capacity Estimation</div>
          <div style={{ color: '#94a3b8', fontSize: 12, marginTop: 4 }}>
            Convert product assumptions into traffic, bandwidth and storage requirements.
          </div>
        </div>
        <button onClick={applyToNfrs} style={applyButtonStyle}>Apply to NFRs</button>
      </div>

      <div style={contentGridStyle}>
        <section style={sectionStyle}>
          <div style={sectionTitleStyle}>ASSUMPTIONS</div>
          <div style={inputGridStyle}>
            {INPUTS.map((input) => (
              <label key={input.key} style={fieldStyle}>
                <span style={{ fontSize: 12, fontWeight: 700 }}>{input.label}</span>
                <span style={{ color: '#64748b', fontSize: 10 }}>{input.description}</span>
                <input
                  type="number"
                  min={input.min}
                  max={input.max}
                  step={input.step ?? 1}
                  value={capacity[input.key]}
                  onChange={(event) => setCapacity({
                    ...capacity,
                    [input.key]: Number(event.target.value),
                  })}
                  style={inputStyle}
                />
              </label>
            ))}
          </div>
        </section>

        <section style={sectionStyle}>
          <div style={sectionTitleStyle}>TRAFFIC</div>
          <div style={metricGridStyle}>
            <Metric label="Daily requests" value={formatCompactNumber(estimate.dailyRequests)} />
            <Metric label="Average QPS" value={formatCompactNumber(estimate.averageQps)} />
            <Metric label="Peak QPS" value={formatCompactNumber(estimate.peakQps)} accent />
            <Metric label="Peak read QPS" value={formatCompactNumber(estimate.peakReadQps)} />
            <Metric label="Peak write QPS" value={formatCompactNumber(estimate.peakWriteQps)} />
          </div>

          <div style={{ ...sectionTitleStyle, marginTop: 22 }}>BANDWIDTH & STORAGE</div>
          <div style={metricGridStyle}>
            <Metric label="Ingress / second" value={formatBytes(estimate.ingressBytesPerSecond)} />
            <Metric label="Egress / second" value={formatBytes(estimate.egressBytesPerSecond)} />
            <Metric label="Raw storage / day" value={formatBytes(estimate.dailyStorageBytes)} />
            <Metric label="Retention + replicas" value={formatBytes(estimate.retainedStorageBytes)} accent />
            <Metric label="Replicated / year" value={formatBytes(estimate.yearlyReplicatedStorageBytes)} />
          </div>
        </section>
      </div>

      <section style={{ ...sectionStyle, marginTop: 16 }}>
        <div style={sectionTitleStyle}>ARCHITECTURE CAPACITY CHECK</div>
        {components.length === 0 ? (
          <div style={emptyStyle}>
            Add and configure architecture components to compare estimated traffic with available throughput.
          </div>
        ) : (
          <div style={{ display: 'grid', gap: 12, gridTemplateColumns: 'repeat(2, minmax(240px, 1fr))', marginTop: 14 }}>
            <CapacityCheck
              label="Read throughput"
              required={estimate.peakReadQps}
              available={readCapacity}
            />
            <CapacityCheck
              label="Write throughput"
              required={estimate.peakWriteQps}
              available={writeCapacity}
            />
          </div>
        )}
      </section>
    </div>
  );
}

function Metric({ label, value, accent }: { label: string; value: string; accent?: boolean }) {
  return (
    <div style={metricStyle}>
      <div style={{ color: '#94a3b8', fontSize: 11 }}>{label}</div>
      <div style={{ color: accent ? '#fb923c' : '#f8fafc', fontSize: 20, fontWeight: 800, marginTop: 6 }}>
        {value}
      </div>
    </div>
  );
}

function CapacityCheck({
  label,
  required,
  available,
}: {
  label: string;
  required: number;
  available: number;
}) {
  const sufficient = available >= required;
  const utilization = available > 0 ? Math.min(100, (required / available) * 100) : 100;
  return (
    <div style={checkStyle}>
      <div style={{ alignItems: 'center', display: 'flex', justifyContent: 'space-between' }}>
        <strong style={{ fontSize: 13 }}>{label}</strong>
        <span style={{ color: sufficient ? '#4ade80' : '#f87171', fontSize: 11, fontWeight: 800 }}>
          {sufficient ? 'SUFFICIENT' : 'INSUFFICIENT'}
        </span>
      </div>
      <div style={{ color: '#94a3b8', display: 'flex', fontSize: 11, justifyContent: 'space-between', marginTop: 10 }}>
        <span>Required: {formatCompactNumber(required)} QPS</span>
        <span>Available: {formatCompactNumber(available)} QPS</span>
      </div>
      <div style={barStyle}>
        <div
          style={{
            background: sufficient ? '#22c55e' : '#ef4444',
            borderRadius: 4,
            height: '100%',
            width: `${utilization}%`,
          }}
        />
      </div>
    </div>
  );
}

const workspaceStyle: React.CSSProperties = {
  background: '#0f172a',
  boxSizing: 'border-box',
  color: '#e2e8f0',
  height: '100%',
  overflowY: 'auto',
  padding: 22,
};

const headingStyle: React.CSSProperties = {
  alignItems: 'center',
  display: 'flex',
  justifyContent: 'space-between',
};

const contentGridStyle: React.CSSProperties = {
  display: 'grid',
  gap: 16,
  gridTemplateColumns: 'minmax(360px, 0.9fr) minmax(440px, 1.1fr)',
  marginTop: 18,
};

const sectionStyle: React.CSSProperties = {
  background: '#172033',
  border: '1px solid #334155',
  borderRadius: 10,
  padding: 16,
};

const sectionTitleStyle: React.CSSProperties = {
  color: '#94a3b8',
  fontSize: 11,
  fontWeight: 800,
  letterSpacing: '0.08em',
};

const inputGridStyle: React.CSSProperties = {
  display: 'grid',
  gap: 12,
  gridTemplateColumns: 'repeat(2, minmax(150px, 1fr))',
  marginTop: 14,
};

const fieldStyle: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  gap: 4,
};

const inputStyle: React.CSSProperties = {
  background: '#0f172a',
  border: '1px solid #475569',
  borderRadius: 6,
  color: '#e2e8f0',
  marginTop: 3,
  padding: '8px 9px',
};

const metricGridStyle: React.CSSProperties = {
  display: 'grid',
  gap: 10,
  gridTemplateColumns: 'repeat(auto-fit, minmax(135px, 1fr))',
  marginTop: 14,
};

const metricStyle: React.CSSProperties = {
  background: '#0f172a',
  border: '1px solid #334155',
  borderRadius: 8,
  padding: 12,
};

const applyButtonStyle: React.CSSProperties = {
  background: '#ea580c',
  border: 'none',
  borderRadius: 7,
  color: '#fff',
  cursor: 'pointer',
  fontSize: 12,
  fontWeight: 800,
  padding: '9px 13px',
};

const emptyStyle: React.CSSProperties = {
  border: '1px dashed #475569',
  borderRadius: 8,
  color: '#64748b',
  fontSize: 12,
  marginTop: 14,
  padding: 20,
  textAlign: 'center',
};

const checkStyle: React.CSSProperties = {
  background: '#0f172a',
  border: '1px solid #334155',
  borderRadius: 8,
  padding: 14,
};

const barStyle: React.CSSProperties = {
  background: '#334155',
  borderRadius: 4,
  height: 6,
  marginTop: 10,
  overflow: 'hidden',
};
